# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build WASM
      run: GOOS=js GOARCH=wasm go build -o ./web/test.wasm ./cmd/wasm/main.go

    - name: Build CLI
      run: go build -o ./bin/ ./cmd/cli/main.go

    - name: Test
      run: go test -v ./...
    
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./bin/*
          ./web/*
        generate_release_notes: true
        name: Release ${{ github.ref }}
        target_commitish: ${{ github.sha }}