name: Build and Release

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Unit Tests
        run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Code Coverage
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: coverage
          path: coverage.txt

  build_cli:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os:
          - 'darwin'
          - 'linux'
        arch:
          - 'amd64'
          - 'arm64'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build CLI
      run: GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -o "./bin/fabled-story-book-${{matrix.os}}-${{matrix.arch}}" ./cmd/cli/main.go 

    - name: Artifact Upload
      uses: actions/upload-artifact@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: fabled-story-book-${{matrix.os}}-${{matrix.arch}}
        path: bin/*

  build_web:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: acifani/setup-tinygo@v2
      with:
        tinygo-version: '0.30.0'
    - name: Build WASM
      run: GOOS=js GOARCH=wasm tinygo build -o ./web/test.wasm -target wasm -no-debug ./cmd/wasm/main.go
    - name: Artifact Upload
      uses: actions/upload-artifact@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: wasm
        path: web/test.wasm

  publish_release:
    runs-on: ubuntu-latest
    needs: [build_cli, build_web]
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/*
        generate_release_notes: true
        name: Release Web ${{ github.ref_name }}
        target_commitish: ${{ github.sha }}