name = "fabled-story-book"
compatibility_date = "2024-02-23"

[build]
command = "npm run build"
watch_dir = "./src"
cwd = "./"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SECTIONS"
id = "560c3342fd144653b6e49de4962a7bf9"
